--
-- p o s i x . n e t i n e t . t c p
--
local M = { }

M.TCP_NODELAY			= 1
M.TCP_MAXSEG			= 2
M.TCP_CORK			= 3
M.TCP_KEEPIDLE			= 4
M.TCP_KEEPINTVL			= 5
M.TCP_KEEPCNT			= 6
M.TCP_SYNCNT			= 7
M.TCP_LINGER2			= 8
M.TCP_DEFER_ACCEPT		= 9
M.TCP_WINDOW_CLAMP		= 10
M.TCP_INFO			= 11
M.TCP_QUICKACK			= 12
M.TCP_CONGESTION		= 13
M.TCP_MD5SIG			= 14
M.TCP_COOKIE_TRANSACTIONS	= 15
M.TCP_THIN_LINEAR_TIMEOUTS	= 16
M.TCP_THIN_DUPACK		= 17
M.TCP_USER_TIMEOUT		= 18
M.TCP_REPAIR			= 19
M.TCP_REPAIR_QUEUE		= 20
M.TCP_QUEUE_SEQ			= 21
M.TCP_REPAIR_OPTIONS		= 22
M.TCP_FASTOPEN			= 23
M.TCP_TIMESTAMP			= 24
M.TCP_NOTSENT_LOWAT		= 25
M.TCP_CC_INFO			= 26
M.TCP_SAVE_SYN			= 27
M.TCP_SAVED_SYN			= 28

return M
