--
-- p o s i x . n e t i n e t . t c p
--
local tcp = { }

tcp.TCP_NODELAY			= 1
tcp.TCP_MAXSEG			= 2
tcp.TCP_CORK			= 3
tcp.TCP_KEEPIDLE		= 4
tcp.TCP_KEEPINTVL		= 5
tcp.TCP_KEEPCNT			= 6
tcp.TCP_SYNCNT			= 7
tcp.TCP_LINGER2			= 8
tcp.TCP_DEFER_ACCEPT		= 9
tcp.TCP_WINDOW_CLAMP		= 10
tcp.TCP_INFO			= 11
tcp.TCP_QUICKACK		= 12
tcp.TCP_CONGESTION		= 13
tcp.TCP_MD5SIG			= 14
tcp.TCP_COOKIE_TRANSACTIONS	= 15
tcp.TCP_THIN_LINEAR_TIMEOUTS	= 16
tcp.TCP_THIN_DUPACK		= 17
tcp.TCP_USER_TIMEOUT		= 18
tcp.TCP_REPAIR			= 19
tcp.TCP_REPAIR_QUEUE		= 20
tcp.TCP_QUEUE_SEQ		= 21
tcp.TCP_REPAIR_OPTIONS		= 22
tcp.TCP_FASTOPEN		= 23
tcp.TCP_TIMESTAMP		= 24
tcp.TCP_NOTSENT_LOWAT		= 25
tcp.TCP_CC_INFO			= 26
tcp.TCP_SAVE_SYN		= 27
tcp.TCP_SAVED_SYN		= 28

return tcp
